version: "3.9"

services:
  proxy:
    build:
      context: .
      dockerfile: ./proxy/Dockerfile
      args:
        - "REACT_APP_API_HOST=$API_HOST"
        - "REACT_APP_API_ROOT=$API_ROOT"
    restart: on-failure
    env_file: .env
    networks:
      - proxy
    ports:
      - 80:80

  redis:
    build: ./redis
    restart: on-failure
    secrets:
      - redis_password
    environment:
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
    networks:
      - db

  server:
    depends_on:
      - redis
    build: ./server
    restart: on-failure
    secrets:
      - redis_password
    env_file: .env
    environment:
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
    networks:
      - proxy
      - db

networks:
  proxy:
  db:

secrets:
  redis_password:
    file: .REDIS_PASSWORD
