version: "3.9"

services:
  client:
    build: ./client
    command: yarn start
    ports:
      - 3000:3000
    volumes:
      - ./client:/client
    tty: true

  server:
    build: ./server
    command: deno run --allow-net ./webserver.ts
    ports:
      - 8000:8000
    volumes:
      - ./server:/server
    tty: true
