version: "3.9"

services:
  proxy:
    build:
      context: .
      dockerfile: ./proxy/Dockerfile
      args:
        - "REACT_APP_API_HOST=$API_HOST"
        - "REACT_APP_API_ROOT=$API_ROOT"
    env_file: .env
    restart: on-failure
    networks:
      - proxy
    ports:
      - 80:80

  redis:
    image: redis
    networks:
      - db

  server:
    build: ./server
    env_file: .env
    restart: on-failure
    networks:
      - proxy
      - db

networks:
  proxy:
  db:
