version: "3.7"

services:
  models:
    build:
      context: ./server
      target: model_generator
    environment:
      GENERATED_TYPES_OUT_DIR: ../client/generated_types
    volumes:
      - ./client:/client
      - ./server:/server
      - /server/model_generator/node_modules/

  client:
    build: ./client
    environment:
      CHOKIDAR_USEPOLLING: "true"
      REACT_APP_ENV: development
      REACT_APP_API_HOST: "http://localhost:8000"
      REACT_APP_API_ROOT: "/"
    ports:
      - 3000:3000
    volumes:
      - ./client:/client
      - /client/node_modules/

  redis:
    build: ./redis
    secrets:
      - redis_password
    environment:
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

  database:
    build: ./database
    secrets:
      - postgres_password
    env_file: .env
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    ports:
      - 5432:5432

  server:
    depends_on:
      - redis
      - database
    build:
      context: ./server
      target: debug
    secrets:
      - redis_password
      - postgres_password
    env_file: .env
    environment:
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      FLASK_ENV: development
      CORS_ALLOWED_ORIGIN: "http://localhost:3000"
    ports:
      - 5678:5678
      - "8000:$API_PORT"
    volumes:
      - ./server:/server

secrets:
  redis_password:
    file: .REDIS_PASSWORD
  postgres_password:
    file: .POSTGRES_PASSWORD
