version: "3.9"

services:
  proxy:
    build:
      context: .
      dockerfile: ./proxy/Dockerfile
    ports:
      - 80:80

  server:
    build: ./server
    command: deno run --allow-net --allow-read ./webserver.ts
    ports:
      - 8000:8000
    networks:
      default:
        aliases:
          - backend
