version: "3.9"

services:
  client:
    build: ./client
    command: yarn start
    environment:
      REACT_APP_API_ROOT: "http://localhost:8000"
    ports:
      - 3000:3000
    volumes:
      - ./client:/client

  server:
    build: ./server
    command: poetry run flask run -h 0.0.0.0 -p $BACKEND_PORT
    env_file: .env
    environment:
      FLASK_ENV: development
      FLASK_APP: "server/app.py"
      CORS_ORIGINS: "http://localhost:3000"
    ports:
      - "8000:${BACKEND_PORT}"
    volumes:
      - ./server:/server
