version: "3.7"

services:
  proxy:
    depends_on:
      - server
    build:
      context: .
      dockerfile: ./proxy/Dockerfile
      args:
        - "REACT_APP_API_HOST=$API_HOST"
        - "REACT_APP_API_ROOT=$API_ROOT"
    restart: on-failure
    env_file: .env
    networks:
      - proxy
    ports:
      - 80:80

  redis:
    build: ./redis
    restart: on-failure
    secrets:
      - redis_password
    environment:
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
    networks:
      - db

  database:
    build: ./database
    restart: on-failure
    secrets:
      - postgres_password
    env_file: .env
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    ports:
      - 5432:5432
    networks:
      - db

  server:
    depends_on:
      - redis
    build:
      context: ./server
      target: production
    restart: on-failure
    secrets:
      - redis_password
      - postgres_password
    env_file: .env
    environment:
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    networks:
      - proxy
      - db

networks:
  proxy:
  db:

secrets:
  redis_password:
    file: .REDIS_PASSWORD
  postgres_password:
    file: .POSTGRES_PASSWORD
