version: "3.9"

services:
  client:
    build: ./client
    command: yarn start
    environment:
      REACT_APP_API_HOST: "http://localhost:8000"
      REACT_APP_API_ROOT: "/"
    ports:
      - 3000:3000
    volumes:
      - ./client:/client
      - /client/node_modules/

  redis:
    build: ./redis
    secrets:
      - redis_password
    environment:
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

  server:
    depends_on:
      - redis
    build: ./server
    command: poetry run uvicorn main:app --host 0.0.0.0 --port $API_PORT --reload --reload-dir server
    secrets:
      - redis_password
    env_file: .env
    environment:
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
      FLASK_ENV: development
      CORS_ALLOWED_ORIGIN: "http://localhost:3000"
    ports:
      - "8000:$API_PORT"
    volumes:
      - ./server:/server

secrets:
  redis_password:
    file: .REDIS_PASSWORD
