version: "3.9"

services:
  proxy:
    build:
      context: .
      dockerfile: ./proxy/Dockerfile
    ports:
      - 80:80

  server:
    build: ./server
    networks:
      default:
        aliases:
          - backend
