version: "3.9"

services:
  client:
    build: ./client
    command: yarn start
    environment:
      REACT_APP_API_HOST: "http://localhost:8000"
      REACT_APP_API_ROOT: "/"
    ports:
      - 3000:3000
    volumes:
      - ./client:/client

  server:
    build: ./server
    command: poetry run python -m server.app
    env_file: .env
    environment:
      FLASK_ENV: development
      FLASK_PROPAGATE_EXCEPTIONS: "False"
      CORS_ALLOWED_ORIGIN: "http://localhost:3000"
    ports:
      - "8000:$API_PORT"
    volumes:
      - ./server:/server
