[tool.poetry]
name = "server"
version = "0.1.0"
description = ""
authors = []

[tool.isort]
profile = "black"
src_paths = ["server", "wsgi.py"]

[tool.taskipy.tasks]
pre_format = "isort ."
format = "black server wsgi.py"

[tool.poetry.dependencies]
python = "^3.9"
flask = "^1.1.2"
gunicorn = "^20.0.4"
flask-cors = "^3.0.9"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.6.4"
taskipy = "^1.6.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
