[tool.poetry]
name = "server"
version = "0.1.0"
description = ""
authors = []

[tool.isort]
profile = "black"
src_paths = ["models", "server", "wsgi.py"]

[tool.black]
line-length = 90
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | \.venv
)/
'''

[tool.pylint.messages_control]
disable = [
  "missing-module-docstring",
  "missing-class-docstring",
  "missing-function-docstring",
  "unsubscriptable-object"
]

[tool.taskipy.tasks]
pre_format = "isort ."
format = "black ."
pre_lint = "task format"
lint = "task lint_mypy && task lint_pylint"
lint_mypy = "mypy --check-untyped-defs models server wsgi.py"
lint_pylint = "pylint models server wsgi.py"

[tool.poetry.dependencies]
python = "^3.9"
eventlet = "^0.30.0"
flask = "^1.1.2"
flask-cors = "^3.0.9"
flask-socketio = "^5.0.1"
gunicorn = "^20.0.4"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.6.4"
mypy = "^0.790"
pylint = "^2.6.0"
taskipy = "^1.6.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
